### ISSUE TITLE
May I ask what version number you use for gradio? This prevents me from running the code normally. Thank you.

### ISSUE THREAD

**Issue by happyflying-web** [zcczhang/UVD#3]
May I ask what version number you use for gradio? This prevents me from running the code normally. Thank you.

**Comment by happyflying-web** [comment]
when I run demo.py, after uploading the video on the website,the terminal shows the following error
`Traceback (most recent call last):
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gradio/blocks.py", line 1438, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gradio/blocks.py", line 1339, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/dellpc/anaconda3/envs/uvd/lib/python3.9/site-packages/gradio/components/gallery.py", line 187, in postprocess
    for img in y:
TypeError: 'Gallery' object is not iterable`

**Comment by zcczhang** [comment]
Hi @happyflying-web, Thanks for the interest! I am using `gradio==3.48.0` at that time before the recent gradio update. Please downgrade the gradio and let me know if there are any problems!

**Comment by happyflying-web** [comment]
Thank you for the version number, it is useful to me！
